# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [8]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [23]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',sep=',',header=None)
iris.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

### Step 4. Create columns for the dataset

In [57]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

In [24]:
iris.columns = ['sl','sw','pl','pw','class']
iris.head()

    sl   sw   pl   pw        class
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [ ]:
iris.isna().sum()
# pd.isnull(iris).sum()

sl       0
sw       0
pl       0
pw       0
class    0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [ ]:
iris.loc[10:29,'pl'] = np.nan #
iris.head(12)

     sl   sw   pl   pw        class
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  NaN  0.2  Iris-setosa
11  4.8  3.4  NaN  0.2  Iris-setosa

In [27]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sl      150 non-null    float64
 1   sw      150 non-null    float64
 2   pl      130 non-null    float64
 3   pw      150 non-null    float64
 4   class   150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

### Step 7. Good, now lets substitute the NaN values to 1.0

In [28]:
iris.fillna(1.0,inplace=True)
iris.head(12)

     sl   sw   pl   pw        class
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.0  0.2  Iris-setosa
11  4.8  3.4  1.0  0.2  Iris-setosa

### Step 8. Now let's delete the column class

In [29]:
del iris['class']

### Step 9.  Set the first 3 rows as NaN

In [ ]:
iris.loc[:2] = np.nan
iris.head()

    sl   sw   pl   pw
0  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

### Step 10.  Delete the rows that have NaN

In [31]:
iris.dropna(axis='index',how='any',inplace=True)
iris.head()

    sl   sw   pl   pw
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
5  5.4  3.9  1.7  0.4
6  4.6  3.4  1.4  0.3
7  5.0  3.4  1.5  0.2

### Step 11. Reset the index so it begins with 0 again

In [ ]:
iris.reset_index(drop=True,inplace=True) #
iris.head()

    sl   sw   pl   pw
0  4.6  3.1  1.5  0.2
1  5.0  3.6  1.4  0.2
2  5.4  3.9  1.7  0.4
3  4.6  3.4  1.4  0.3
4  5.0  3.4  1.5  0.2